(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/cc-nav-swiper/cc-nav-swiper"],{"176e":function(n,t,e){"use strict";e.r(t);var i=e("c49d"),r=e.n(i);for(var u in i)["default"].indexOf(u)<0&&function(n){e.d(t,n,(function(){return i[n]}))}(u);t["default"]=r.a},3642:function(n,t,e){},"4b66":function(n,t,e){"use strict";var i=e("3642"),r=e.n(i);r.a},"5d2a":function(n,t,e){"use strict";e.r(t);var i=e("bb07"),r=e("176e");for(var u in r)["default"].indexOf(u)<0&&function(n){e.d(t,n,(function(){return r[n]}))}(u);e("4b66");var o=e("f0c5"),c=Object(o["a"])(r["default"],i["b"],i["c"],!1,null,"ba8646aa",null,!1,i["a"],void 0);t["default"]=c.exports},bb07:function(n,t,e){"use strict";e.d(t,"b",(function(){return r})),e.d(t,"c",(function(){return u})),e.d(t,"a",(function(){return i}));var i={uniGrid:function(){return e.e("components/uni-grid/uni-grid").then(e.bind(null,"d0a6"))},uniGridItem:function(){return e.e("components/uni-grid-item/uni-grid-item").then(e.bind(null,"6f34"))}},r=function(){var n=this,t=n.$createElement,e=(n._self._c,n.__map(n.pageDataList,(function(t,e){var i=n.__get_orig(t),r=n.__map(t,(function(t,e){var i=n.__get_orig(t),r=n._f("toTitle")(t.title);return{$orig:i,f0:r}}));return{$orig:i,l0:r}})));n.$mp.data=Object.assign({},{$root:{l1:e}})},u=[]},c49d:function(n,t,e){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var i={components:{uniGrid:function(){e.e("components/uni-grid/uni-grid").then(function(){return resolve(e("d0a6"))}.bind(null,e)).catch(e.oe)},uniGridItem:function(){e.e("components/uni-grid-item/uni-grid-item").then(function(){return resolve(e("6f34"))}.bind(null,e)).catch(e.oe)}},props:{square:{type:Boolean,default:!0},rowCount:{type:[Number,String],default:2},columnCount:{type:[Number,String],default:2},list:{type:Array,required:!0,default:function(){return[]}}},computed:{pageDataList:function(){for(var n=this.rowCount*this.columnCount,t=this.list.length/n,e=[],i=0;i<t;++i)e[i]=this.list.slice(i*n,(i+1)*n);return e}},methods:{itemClick:function(n){this.$emit("itemClick",n)}},filters:{toTitle:function(n){return n.length>6?n.substring(0,6)+"...":n}}};t.default=i}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/cc-nav-swiper/cc-nav-swiper-create-component',
    {
        'components/cc-nav-swiper/cc-nav-swiper-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("5d2a"))
        })
    },
    [['components/cc-nav-swiper/cc-nav-swiper-create-component']]
]);
